# 集群版
spring:
  application:
    # 指定profile=eureka-server1
    profiles: eureka-server1
    name: EUREKA-HA
server:
  port: 10086
eureka:
  instance:
    # 指定当profile=eureka-server1时，主机名是eureka-server1
    hostname: 127.0.0.1
  client:
    service-url:
      # 将自己注册到eureka-server1、eureka-server2这个Eureka上面去
      defaultZone: http://127.0.0.1:10086/eureka/
